version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8088"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:567234@localhost:8088/hw_13"
      SECRET_KEY: "your-secret-key"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

  # Додайте інші сервіси, які ваш додаток може використовувати, якщо потрібно
